In [1]:
using(LinearAlgebra)
A = rand(1000, 1000)
x = rand(1000)
b = A*x

1000-element Array{Float64,1}:
 253.3083276849195 
 243.05911474818893
 246.11078789302942
 237.85762520000162
 245.5549805445389 
 245.78824188201287
 247.79700974268073
 246.2511535759747 
 250.81677280182552
 251.08368744086346
 248.43288833573828
 249.37126300861345
 244.05255248722776
   ⋮               
 246.7132972815807 
 242.90191036712022
 246.73668344936564
 234.0140419422764 
 235.58936193379193
 249.44309246502218
 255.6977803246507 
 254.5722963174516 
 235.47579173640338
 248.75859437119772
 248.433236718044  
 245.46429252266003

In [6]:
invX = inv(A) * b
divX = A \ b
AF= factorize(A)
factX =  AF \ b

invTime = @elapsed inv(A) * b
divTime = @elapsed  A \ b
factTime = @elapsed factorize(A)
factTime += @elapsed AF \ b

print("Inverse  time ")
println(invTime)
print("Operator \\ time ")
println(divTime)
print("Factorize time ")
println(factTime)

Inverse  time 0.194084148
Operator \ time 0.103735224
Factorize time 0.096503178


In [7]:
println("Błąd")
print("Inverse ")
invDeltaX = x - invX
println(sqrt(dot(invDeltaX,invDeltaX)))

divDeltaX = x -  divX
print("Operator \\ ")
println(sqrt(dot(divDeltaX,divDeltaX)))

factDeltaX = x - factX

print("Factorize ")
println(sqrt(dot(factDeltaX,factDeltaX)))

Błąd
Inverse 3.9669335616345097e-11
Operator \ 1.1583239406514014e-11
Factorize 1.1583239406514014e-11


In [5]:
using CSV
using DataFrames
using Plots
using Polynomials
using Statistics
input="result3.csv"
df=CSV.read(input, delim=",")
df3=by(df, [:size]) do subGroup
          DataFrame(meanNaive = mean(subGroup[:time_naive]), stdNaive = std(subGroup[:time_naive]),
            meanBetter = mean(subGroup[:time_better]), stdBetter = std(subGroup[:time_better]),
            meanBlas = mean(subGroup[:time_gsl]), stdBlas = std(subGroup[:time_gsl])) 
        end
y = df3[:meanNaive]
x = [100,150,200,250,300,350,400,450,500,550]
A=zeros(10,4)
A[:,1] = x.^3
A[:,2] = x.^2
A[:,3] = x
A[:,4] = ones(10)
A \ y


4-element Array{Float64,1}:
       4.564486305982914   
     445.2705881818063     
 -203522.8530831342        
       1.8216191152120616e7

In [6]:
polyfit(x, y,3)

Poly(1.8216191152120616e7 - 203522.8530831342*x + 445.2705881818063*x^2 + 4.564486305982914*x^3)

In [7]:
using(LinearAlgebra)
A = zeros(4,3)
A[:,1] = [1 1 1 1]
A[:,2] = [-1, 4, 4, -1]
A[:,3] = [4 -2 2 0]

1×4 Array{Int64,2}:
 4  -2  2  0

In [8]:
AF=factorize(A)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
4×4 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.171499  -0.800368    0.282843  -0.5
  0.685994   0.315296    0.424264  -0.5
  0.685994  -0.509325   -0.141421   0.5
 -0.171499   0.0242536   0.848528   0.5
R factor:
3×3 Array{Float64,2}:
 5.83095  -0.685994   1.02899 
 0.0      -4.85071   -0.970143
 0.0       0.0        1.41421 
permutation:
3-element Array{Int64,1}:
 2
 3
 1

In [9]:
inv(AF.R)

3×3 Array{Float64,2}:
 0.171499  -0.0242536  -0.141421
 0.0       -0.206155   -0.141421
 0.0        0.0         0.707107

In [10]:
Transpose(AF.Q)*AF.Q

4×4 Array{Float64,2}:
  1.0          2.38524e-16  -1.38778e-16  1.94289e-16
  2.38524e-16  1.0           6.59195e-17  1.73472e-18
 -1.38778e-16  6.59195e-17   1.0          0.0        
  1.94289e-16  1.73472e-18   0.0          1.0        